##Python Programming

In [ ]:
print ('Welcome to Python Programming')
print ("Basic Python Programming")

print ("My name's Tissana")

print (100)
print (375.5)

print()

print ("100")

print (100 + 200)
print ("100"+"200")

# print (100 + "200")

Welcome to Python Programming
Basic Python Programming
My name's Tissana
100
375.5

100
300
100200

In [ ]:
mydata = 30
print(f'Date : {mydata}')

language = 'Python'
title = f'This is {language} Programming'
print(title)

print(f"{language} for Data Analytics")

home = 0
away = 6
result = F"ManU {home} - {away} Liverpool"
print(result)

Date : 30
This is Python Programming
Python for Data Analytics
ManU 0 - 6 Liverpool

## String

In [ ]:
mystring = "Python Programming"

print("mystring[7] :" , mystring[7])
print("mystring[1:5] :" , mystring[1:5])

mystring[7] : P
mystring[1:5] : ytho

In [ ]:
mystring = 'Python'

print("mystring[-1]: ", mystring[-1])
print("mystring[-2]: ", mystring[-2])
print("mystring[-6]: ", mystring[-6])

mystring[-1]:  n
mystring[-2]:  o
mystring[-6]:  P

In [ ]:
mystring = "Welcome to Python Programming"

print('mystring[5] : ', mystring[5])
print('mystring[2:10] : ', mystring[2:10])
print('mystring[2:18:2] : ', mystring[2:18:2])
print('mystring[:8] : ', mystring[:8])
print('mystring[8:] : ', mystring[8:])
print('mystring[::3] : ', mystring[::3])
print('mystring[::-2] : ', mystring[::-2])

mystring[5] :  m
mystring[2:10] :  lcome to
mystring[2:18:2] :  loet yhn
mystring[:8] :  Welcome
mystring[8:] :  to Python Programming
mystring[::3] :  WceoyoPgmn
mystring[::-2] :  gimroPnhy teolW

#List

In [ ]:
mylst = [10, 20, 30, 40, 'Python', 50, 'Java']
print(mylst)
print(type(mylst))

print('------------------------------')

mylist1 = [] # Empty List
mylist2 = [10, 20, 30, 40, 50]
mylist3 = ["Thailand", "Singapore", "Malaysia", "Vietnam"]
mylist4 = ['Python', 'Java', 1994, 1996]
mylist5 = ["Name", "Surname", 300, 0.5, mylist2]

print(mylist1)
print(mylist2)
print(mylist3)
print(mylist4)
print(mylist5)

[10, 20, 30, 40, 'Python', 50, 'Java']
<class 'list'>
------------------------------

In [ ]:
mylist1 = ['Thailand', 'Vietnam', 2017, 2021]
mylist2 = [100, 200, 300, 400, 500, 600, 700, 800]

print("mylist1[0]: ", mylist1[0])
print("mylist1[-1]: ", mylist1[-1])
print("mylist2[3]: ", mylist2[3])
print("mylist2[-5]: ", mylist2[-5])
print("mylist2[1:5]: ", mylist2[1:5])
print("mylist2[::2]: ", mylist2[::2])
print("mylist2[2::2]: ", mylist2[2::2])
print("mylist2[2:8:2]: ", mylist2[2:8:2])
print("mylist2[:8]: ", mylist2[:8])
print("mylist2[5:]: ", mylist2[5:])

mylist1[0]:  Thailand
mylist1[-1]:  2021
mylist2[3]:  400
mylist2[-5]:  400
mylist2[1:5]:  [200, 300, 400, 500]
mylist2[::2]:  [100, 300, 500, 700]
mylist2[2::2]:  [300, 500, 700]
mylist2[2:8:2]:  [300, 500, 700]
mylist2[:8]:  [100, 200, 300, 400, 500, 600, 700, 800]
mylist2[5:]:  [600, 700, 800]

In [ ]:
mylist1 = ['Thailand', 'Vietnam', 2017, 2021]
print("Old Value : ", mylist1[2])

mylist1[2] = 2023
print("New Value : ", mylist1[2])

print('-------------------------')


mylist2 = ['Python', 'c#', 1994, 2000]
print("Before deleting : ", mylist2)

del mylist2[2]
print("After deleting : ", mylist2)

Old Value :  2017
New Value :  2023
-------------------------
Before deleting :  ['Python', 'c#', 1994, 2000]
After deleting :  ['Python', 'c#', 2000]

In [ ]:
mylst = [i*1 for i in range(10)]

print("List Member: ", mylst)
print('-------------------------')

del mylst[0], mylst[2], mylst[4]
print("List After Remove Member: ", mylst)
print('-------------------------')

#del mylst
#print("List After Remove Member: ", mylst)

List Member:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
-------------------------
List After Remove Member:  [1, 2, 4, 5, 7, 8, 9]
-------------------------

#Tuple

In [ ]:
mytup1 = (100, 50.75)
mytup2 = ('Python', 'Java')
mytup3 = (30, 15.5, "Thailand", "Malaysia")
mytup4 = (mytup1, mytup2, mytup3)
mytup5 = mytup1 + mytup2
mytup6 = ()

print(mytup1)
print(mytup2)
print(mytup3)
print(mytup4)
print(mytup5)
print(mytup6)

print(type(mytup1))

(100, 50.75)
('Python', 'Java')
(30, 15.5, 'Thailand', 'Malaysia')
((100, 50.75), ('Python', 'Java'), (30, 15.5, 'Thailand', 'Malaysia'))
(100, 50.75, 'Python', 'Java')
()
<class 'tuple'>

In [ ]:
mytup1 = (("Name", "Sunisa"), ("Age", "38"),("Gender", "Female"))

print(mytup1[0])
print(mytup1[1])
print(mytup1[2])

mytup2 = (100, 35.75)
mytup2[0] = 155
mytup2[1] = 75.55
print(mytup2)

('Name', 'Sunisa')
('Age', '38')
('Gender', 'Female')

TypeError: 'tuple' object does not support item assignment

In [ ]:
mytup = ('Arsenal', 'Manchester City', 2002, 2022)
print(mytup)
print(mytup[0])
print(mytup[1])
print(mytup[2])
print(mytup[3])

#del mytup[2]
#print("After mytup[2] Deleted : ", mytup)

#del mytup
#print(mytup)

('Arsenal', 'Manchester City', 2002, 2022)
Arsenal
Manchester City
2002
2022

NameError: name 'mytup' is not defined

##Dictionary

In [ ]:
mydict1 = {}
mydict2 = {'Arsenal' : '75', 'Liverpool' : '78' , 'Newcastle' : '80'}
mydict3 = {'Aston Villa' : 56}
mydict4 = {'Man U' : 47 , 2023 : 20}

print(mydict1)
print(mydict2)
print(mydict3)
print(mydict4)

print(type(mydict1))

{}
{'Arsenal': '75', 'Liverpool': '78', 'Newcastle': '80'}
{'Aston Villa': 56}
{'Man U': 47, 2023: 20}
<class 'dict'>

In [ ]:
mydict = {'Name' : 'Sunisa' , 'Age' : 30 , 'Class' : 'First'}

print("mydict['Name']: " , mydict['Name'])
print("mydict['Age']: " , mydict['Age'])
print("mydict['Class']: " , mydict['Class'])

mydict['Name']:  Sunisa
mydict['Age']:  30
mydict['Class']:  First

In [ ]:
mydict1 = {}
print("Original Dictionary : ", mydict1)

mydict1['Key1'] = 150
print("Update data1 to dictionary : ", mydict1)

mydict1['Key2'] = 450
print("Update data2 to dictionary : ", mydict1)

Original Dictionary :  {}
Update data1 to dictionary :  {'Key1': 150}
Update data2 to dictionary :  {'Key1': 150, 'Key2': 450}

In [ ]:
mydict = {'Name' : 'Sunisa' , 'Age' : 30 , 'Class' : 'First'}
print("Original Dictionary : ", mydict)

del mydict['Class']
print ("After removed :", mydict)

mydict.clear()
print ("After clear :", mydict)

del mydict
print ("After deleted :", mydict)

Original Dictionary :  {'Name': 'Sunisa', 'Age': 30, 'Class': 'First'}
After removed : {'Name': 'Sunisa', 'Age': 30}
After clear : {}

NameError: name 'mydict' is not defined

In [ ]:
mydic1 = {1:"Python", 2:"Java", 3:"SQL", 4:"R"}
for i in mydic1:
  print(mydic1[i])

mydic2 = {"Lage":"Python", 2:(100, 200), 3:[30, 40, 50], 4:{'Name' : 'Sunisa'}}
for i in mydic2:
  print(mydic2[i])

Python
Java
SQL
R
Python
(100, 200)
[30, 40, 50]
{'Name': 'Sunisa'}

##if statements

In [ ]:
myname = input ("Enter name :")
price = float(input("Enter price of %s :" %myname))

if price >= 1000:
  temp = price * 0.05
  price = price - temp

vat = price * 0.07
price = price + vat

print("The price of %s (inc VAT 7%%) is %.2f %s and VAT %.2f %s" %(myname, price, "Baht.", vat , "Baht." ))

Enter name :Python Book
Enter price of Python Book :1000
The price of Python Book (inc VAT 7%) is 1016.50 Baht. and VAT 66.50 Baht.

In [ ]:
mynum = int(input ("Enter Integer Number :"))

if mynum % 2 == 0:
  print("%d is Even Number" %mynum)
else:
  print("%d is Odd Number" %mynum)

Enter Integer Number :10
10 is Even Number

In [ ]:
myscore = float(input("Enter your score : "))
mymsg = "Your grade is "

if myscore >= 80:
  print(mymsg + "A")
elif myscore >= 70:
  print(mymsg + "B")
elif myscore >= 60:
  print(mymsg + "C")
elif myscore >= 50:
  print(mymsg + "D")
else
  print(mymsg + "F")

In [ ]:
myvar = 200

if myvar < 200:
  print("Expression value is less than 200")
elif myvar < 500:
  print("Expression value is less than 500")
  if myvar == 400:
    print("Which is 400")
  elif myvar == 300:
    print("Which is 300")
  elif myvar == 200:
    print("Which is 200")
else:
  print("False Expression")

Expression value is less than 500
Which is 200

##While Loop

In [2]:
count = 0

while (count < 10):
  print ('This count is: ', count)
  count = count + 1

print('The End')

This count is:  0
This count is:  1
This count is:  2
This count is:  3
This count is:  4
This count is:  5
This count is:  6
This count is:  7
This count is:  8
This count is:  9
The End

In [3]:
count = 0

while count < 9 :
  print (count, "is less than 9.")
  count = count + 1
else:
  print (count, "is not less than 9.")

0 is less than 9.
1 is less than 9.
2 is less than 9.
3 is less than 9.
4 is less than 9.
5 is less than 9.
6 is less than 9.
7 is less than 9.
8 is less than 9.
9 is not less than 9.

In [ ]:
count = 1
sum = 0.0

print ("Exit this program, please type 0 or 0.0 :")

mynum = float(input("Enter a number : "))

while mynum != 0 or mynum != 0.0:
  sum += mynum  # Sum = sum + mynum
  avg = sum / count
  count += 1    # count = count + 1
  print("Average of number is : ", avg)
  mynum = float(input("Enter a number : "))

In [4]:
for chr in 'Python':
  if chr == 'h':
    break
  print('Current Character :', chr)

print ("--------------------------------")

myvar = 10
while myvar > 0 :
  print ('Current variable value :', myvar)
  myvar = myvar - 1
  if myvar == 5:
    break

Current Character : P
Current Character : y
Current Character : t
--------------------------------
Current variable value : 10
Current variable value : 9
Current variable value : 8
Current variable value : 7
Current variable value : 6

In [7]:
for chr in 'Python':
  if chr == 'h':
    continue
  print('Current Character :', chr)

print ("--------------------------------")

myvar = 10
while myvar > 0 :
  myvar = myvar - 1
  if myvar == 5:
    continue
  print ('Current variable value :', myvar)

Current Character : P
Current Character : y
Current Character : t
Current Character : o
Current Character : n
--------------------------------
Current variable value : 9
Current variable value : 8
Current variable value : 7
Current variable value : 6
Current variable value : 4
Current variable value : 3
Current variable value : 2
Current variable value : 1
Current variable value : 0

In [8]:
for chr in 'Python':
  if chr == 'h':
    pass
    print('This is pass block')
  print('Current Character :', chr)

Current Character : P
Current Character : y
Current Character : t
This is pass block
Current Character : h
Current Character : o
Current Character : n

In [10]:
mynum = int(input("Enter integer number (odd) : "))
flag = False
num = 1

for i in range(3, mynum+2 , 2):  # i = 3
  if flag == False:
    num = num - (1 / i)         # num = 0
    flag = True
  else:
    num = num + (1 / i)
    flag = False
print("result of PI/4 = %.4f" %num)

Enter integer number (odd) : 5
result of PI/4 = 0.8667

#Python for Data Analytics

Series คือโครงสร้างข้อมูลแบบ 1 มิติ ทำหน้าที่เก็บข้อมูลเรียงกันเป็นแถวหรือคอลัมน์เดียว คล้ายกับคอลัมน์ใน Excel หรือ List

Series จะมี Value กับ Index

In [2]:
import pandas as pd
from pandas import Series, DataFrame

In [19]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [21]:
obj.values

array([ 4,  7, -5,  3])

In [22]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [25]:
obj2 = pd.Series([4, 7, -5, 3], index=['a', 'b', 'c', 'd'])
obj2

a    4
b    7
c   -5
d    3
dtype: int64

In [26]:
obj2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [31]:
obj2['d'] = 6
obj2[['d', 'c', 'a']]

d    6
c   -5
a    4
dtype: int64

In [32]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [34]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [35]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [36]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [37]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [40]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

### DataFrame

In [42]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [45]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four', 'five', 'six'])
frame2

       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [47]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [48]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [50]:
frame2

       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [51]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [52]:
frame2

       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [53]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
frame2

       year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [54]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

       year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [56]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

frame3 = pd.DataFrame(pop)
frame3

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [57]:
frame3.T

        2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [3]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

## Reading and Writing Data in Text Format

In [17]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [18]:
df = pd.read_csv('/content/drive/MyDrive/data/ex1.csv')
df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [19]:
pd.read_table('/content/drive/MyDrive/data/ex1.csv', sep=',')

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [20]:
pd.read_csv('/content/drive/MyDrive/data/ex2.csv', header=None)

   0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [21]:
pd.read_csv('/content/drive/MyDrive/data/ex2.csv',
            names=['a', 'b', 'c', 'd', 'message'])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [23]:
names = ['a', 'b', 'c', 'd', 'message']

pd.read_csv('/content/drive/MyDrive/data/ex2.csv',
            names=names, index_col='message')

         a   b   c   d
message
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

In [26]:
parsed = pd.read_csv('/content/drive/MyDrive/data/csv_mindex.csv',
                     index_col=['key1', 'key2'])
parsed

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [27]:
pd.read_csv('/content/drive/MyDrive/data/ex4.csv', skiprows=[0, 2, 3])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [28]:
result = pd.read_csv('/content/drive/MyDrive/data/ex5.csv')
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [29]:
pd.isnull(result)

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

In [33]:
result = pd.read_csv('/content/drive/MyDrive/data/ex5.csv',
                     na_values=['NULL'])
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [35]:
pd.read_csv('/content/drive/MyDrive/data/ex5.csv')

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [37]:
sentinels = {'message': ['foo', 'NA'], 'something': ['two']}
pd.read_csv('/content/drive/MyDrive/data/ex5.csv', na_values=sentinels)

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       NaN  5   6   NaN   8   world
2     three  9  10  11.0  12     NaN

In [38]:
result = pd.read_csv('/content/drive/MyDrive/data/ex6.csv')
result

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

In [39]:
pd.read_csv('/content/drive/MyDrive/data/ex6.csv', nrows=5)

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

### Writing Data to Text Format

In [41]:
data = pd.read_csv('/content/drive/MyDrive/data/ex5.csv')
data

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [42]:
data.to_csv('/content/drive/MyDrive/data/out.csv')

In [47]:
import csv

f = open('/content/drive/MyDrive/data/ex7.csv')

reader = csv.reader(f)

for line in reader:
    print(line)

['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3']

In [50]:
obj = """
{"name": "Wes",
 "places_lived": ["United States", "Spain", "Germany"],
 "pet": null,
 "siblings": [{"name": "Scott", "age": 30, "pets": ["Zeus", "Zuko"]},
              {"name": "Katie", "age": 38, "pets": ["Sixes", "Stache", "Cisco"]}]
}
"""

In [51]:
import json

result = json.loads(obj)
result

{'name': 'Wes',
 'places_lived': ['United States', 'Spain', 'Germany'],
 'pet': None,
 'siblings': [{'name': 'Scott', 'age': 30, 'pets': ['Zeus', 'Zuko']},
  {'name': 'Katie', 'age': 38, 'pets': ['Sixes', 'Stache', 'Cisco']}]}

In [53]:
asjson = json.dumps(result)

siblings = pd.DataFrame(result['siblings'], columns=['name', 'age'])
siblings

    name  age
0  Scott   30
1  Katie   38

In [54]:
data = pd.read_json('/content/drive/MyDrive/data/example.json')
data

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9